config/routes.rb
Rails.application.routes.draw do
  get 'repositories/index'
  get 'repositories/search'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "repositories#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/repositories_controller.rb
# frozen_string_literal: true

# Repositories controller to allow users to search for Github Repositories
class RepositoriesController < ApplicationController
  def index; end

  def search
    search_term = params[:search_term]

    if search_term.nil? || search_term.strip == ''
      format_error('Search keyword cannot be empty')
      return
    end

    @results = GithubApi.new.search_repositories(search_term)
  rescue Octokit::Error => e
    format_error(e.message)
  end

  private

  def format_error(message)
    @error = "Error: #{message}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GithubExplorer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <main class="bg-white dark:bg-gray-900 container mx-auto min-h-screen">
      <%= yield %>
    </main>
  </body>
</html>

app/views/repositories/_header.html.erb
<header class="px-6 pt-28 text-center">
    <div class="mx-auto max-w-lg">
      <h1 class="text-3xl font-bold text-gray-800 dark:text-white md:text-4xl">GitHub Repo Explorer</h1>
      <p class="mt-6 text-gray-500 dark:text-gray-300">Explore GitHub Like Never Before!</p>
      <div
        class="mx-auto mt-6 w-full max-w-sm rounded-md border bg-transparent focus-within:border-blue-400 focus-within:ring focus-within:ring-blue-300 focus-within:ring-opacity-40 dark:border-gray-700 dark:focus-within:border-blue-300">
        <%= form_tag(repositories_search_path, method: 'get' , class: "flex flex-col md:flex-row" ) do %>
          <%= text_field_tag( :search_term, params[:search_term], placeholder: 'Enter to search for repository' ,
            class: "m-1 h-10 flex-1 appearance-none border-none bg-transparent px-4 py-2 text-gray-700 placeholder-gray-400 focus:placeholder-transparent focus:outline-none focus:ring-0 dark:text-gray-200"
            ) %>
          <button type="submit"
            class="m-1 h-10 transform rounded-md bg-blue-500 px-4 py-2 text-white transition-colors duration-300 hover:bg-blue-400 focus:bg-blue-400 focus:outline-none">
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"
              xmlns="http://www.w3.org/2000/svg">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
            </svg>
          </button>
        <% end %>
      </div>
  </div>
</header>

app/views/repositories/index.html.erb
<%= render partial: 'header' %>

app/views/repositories/search.html.erb
<%= render partial: 'header' %>

<section class="mx-auto px-6 pb-28">
  <% if @error %>
    <p class="text-center mt-8 text-gray-500 dark:text-gray-300 font-semibold text-white">
      <%= sanitize @error %>
    </p>
  <% elsif @results.total_count > 0 %>
    <p class="mt-8 text-gray-500 dark:text-gray-300 text-uppercase font-semibold">
      Total: <%= @results.total_count %>
    </p>
    <ul class="mt-1 grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">
      <% @results.items.each do |repo| %>
      <li class="flex bg-white shadow-lg rounded-lg mx-4 md:mx-auto w-full"><!--horizantil margin is just for display-->
        <div class="flex items-start px-4 py-6">
            <img class="w-12 h-12 rounded-full object-cover mr-4 shadow" src=<%= repo.owner.avatar_url %> alt=<%= repo.full_name %>>
            <div class="">
              <div class="flex items-center justify-between">
                  <h2 class="text-lg font-semibold text-gray-900 -mt-1"><%= repo.full_name %></h2>
              </div>
              <p class="text-gray-700 text-sm">Last updated at: <%= repo.updated_at %></p>
              <p class="mt-3 text-gray-700 text-sm">
                <%= repo.description %>
              </p>
              <div class="mt-4 flex items-center">
                <div class="flex mr-3 text-gray-700 text-sm mr-3" title="Stargazers count">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" id="light" width="16px" class="mr-2"><path d="M19 9.199h-.98c-.553 0-1 .359-1 .801 0 .441.447.799 1 .799H19c.552 0 1-.357 1-.799 0-.441-.449-.801-1-.801zM10 4.5A5.483 5.483 0 0 0 4.5 10c0 3.051 2.449 5.5 5.5 5.5 3.05 0 5.5-2.449 5.5-5.5S13.049 4.5 10 4.5zm0 9.5c-2.211 0-4-1.791-4-4 0-2.211 1.789-4 4-4a4 4 0 0 1 0 8zm-7-4c0-.441-.449-.801-1-.801H1c-.553 0-1 .359-1 .801 0 .441.447.799 1 .799h1c.551 0 1-.358 1-.799zm7-7c.441 0 .799-.447.799-1V1c0-.553-.358-1-.799-1-.442 0-.801.447-.801 1v1c0 .553.359 1 .801 1zm0 14c-.442 0-.801.447-.801 1v1c0 .553.359 1 .801 1 .441 0 .799-.447.799-1v-1c0-.553-.358-1-.799-1zm7.365-13.234c.391-.391.454-.961.142-1.273s-.883-.248-1.272.143l-.7.699c-.391.391-.454.961-.142 1.273s.883.248 1.273-.143l.699-.699zM3.334 15.533l-.7.701c-.391.391-.454.959-.142 1.271s.883.25 1.272-.141l.7-.699c.391-.391.454-.961.142-1.274s-.883-.247-1.272.142zm.431-12.898c-.39-.391-.961-.455-1.273-.143s-.248.883.141 1.274l.7.699c.391.391.96.455 1.272.143s.249-.883-.141-1.273l-.699-.7zm11.769 14.031l.7.699c.391.391.96.453 1.272.143.312-.312.249-.883-.142-1.273l-.699-.699c-.391-.391-.961-.455-1.274-.143s-.248.882.143 1.273z"></path></svg>
                <span><%= repo.stargazers_count %></span>
                </div>
                <div class="flex mr-3 text-gray-700 text-sm mr-8" title="Watchers count">
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" id="light" width="16px" class="mr-2">
                  <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M7 10a3 3 0 013-3h8a3 3 0 013 3v8a3 3 0 01-3 3h-8a3 3 0 01-3-3v-8zm3-1a1 1 0 00-1 1v8a1 1 0 001 1h8a1 1 0 001-1v-8a1 1 0 00-1-1h-8z"
                  />
                  <path
                    fill-rule="evenodd"
                    clip-rule="evenodd"
                    d="M3 6a3 3 0 013-3h10a1 1 0 110 2H6a1 1 0 00-1 1v10a1 1 0 11-2 0V6z"
                  />
                </svg>
                  <span><%= repo.watchers_count %></span>
                </div>
              </div>

              <div class="w-full pt-5 mx-auto ">
                <div class="text-sm text-gray-700 py-1">
                  <%= link_to('Learn more', repo.html_url, class: 'text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-3 py-2 text-center inline-flex items-center') %>
                </div>
            </div>
            </div>
        </div>
      </li>
      <% end %>
    </ul>
  <% else %>
    <p class="text-center mt-8 text-gray-500 dark:text-gray-300 font-semibold text-white">
      There are no repositories with given name. Please search for another keyword.
    </p>
  <% end %>
</section>